name: null
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.11.27=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1d=h7b6447c_3
  - pcre=8.43=he6710b0_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py_0
  - python=3.7.5=h0371630_0
  - pytorch=0.4.1=py37_py36_py35_py27__9.0.176_7.1.2_2
  - readline=7.0=h7b6447c_5
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - boto==2.49.0
    - boto3==1.10.32
    - botocore==1.13.32
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.14
    - decorator==4.4.1
    - docutils==0.15.2
    - gensim==3.8.1
    - idna==2.8
    - imageio==2.6.1
    - jmespath==0.9.4
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - llvmlite==0.30.0
    - matplotlib==3.1.2
    - networkx==2.4
    - numba==0.46.0
    - packaging==19.2
    - pandas==0.25.3
    - pillow==6.2.1
    - protobuf==3.11.1
    - pycocotools==2.0.0
    - pyparsing==2.4.5
    - python-dateutil==2.8.0
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyyaml==5.2
    - requests==2.22.0
    - s3transfer==0.2.1
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.3.3
    - sklearn==0.0
    - smart-open==1.9.0
    - sparse==0.8.0
    - tensorboardx==1.9
    - torchvision==0.1.8
    - tqdm==4.40.0
    - urllib3==1.25.7
prefix: pytorchenv3_oltr

